### ISSUE TITLE
Sets not created when diacritis is used in folder name

### ISSUE THREAD

**Issue by kecimalah** [syno2flickr/syno2flickr#10] opened 2014-11-13 20:17 UTC
Hi,
I really like this program, but i have problem with Czech diacritics.
When folder is named with Diacritics for Example "Budapešť 2007" set isnt created and in CMD is shown error: 
Error while create set "Budapešť 2007" for photo ..
Error: Invalid signature (Code: 96)

When is picture named with diacritics there is no problem.

Can you please check it, if is possible to fix it. 

Thank you

**Comment by kecimalah** [comment] 2014-11-24 09:23
Fixed now program removing diacritcs for folder names:

Added under class Syno2Flickr:
    public static String removeAccents(String text) {
        return text == null ? null :
            Normalizer.normalize(text, Form.NFD)
                .replaceAll("\p{InCombiningDiacriticalMarks}+", "");
    }

And edited line 489:
String setName = removeAccents(node.getParent().getFile().getName());

**Comment by syno2flickr** [comment] 2014-11-24 15:21
Hi,
thank you for your feedback. I'll check this ASAP. 

Best regards,
JB

**Comment by syno2flickr** [comment] 2014-11-24 18:10
I can not reproduce your problem. 

I used directory tree :
System directory tree of found files in /Users/jbrek/tmp2:
  Budapešť /
  |  +--Budapešť 2007/
  |  |  +--11535276216_o copy.jpg
  |  |  +--11535276216_o.jpg

And a set "Budapešť 2007" and a collection "Budapešť" were created. 
What is your config? OS? JRE? Region preferences?

**Comment by kecimalah** [comment] 2014-11-24 18:32
I have Windows 8.1 64 bit - czech and JRE 8 update 25
Tryed same as you and same - set isnt created.
With removeAccents is OK, but better would be preserve diacritics, but not big problem without it.

**Comment by syno2flickr** [comment] 2014-11-25 12:48
Ok I tried with Win8 and JRE 8 and I could reproduce the problem. 

If I add the parameter "-Dfile.encoding=UTF8" to the command line it works. 
The full command line looks like:
"java -Dfile.encoding=UTF8  -jar syno2flickr-0.2.1.jar syno2flickr.properties"

Can you try this? Thx
JB

**Comment by kecimalah** [comment] 2014-11-25 16:23
With this parameter it is working OK.
Thank you.

Another thing, tryed uploading around 9000 pictures in 36 folders/sets after around 4 hours and 1500 pictures it shown http error 502, that i can communicate with server and stoped uploading. I havent saved that error, will try uploading it again.  My internet connection is stable, so dont know why it stopped.
Have you tryed uplading that much pictures at once?
Or is it nessesary to upload only few sets at once ? Which will be quite uncofotable, better would be to upload galleries from  whole year at once.

**Comment by syno2flickr** [comment] 2014-11-25 17:13
Nice. I think Windows users should always use this parameter. I will update the README file for next release. 

Yes I already sent more than 2000 pictures or videos successfully. The program isn't flexible and will stop at the first error. 502 http error can not be generated by the program itself, I think the problem come from Flickr servers side. I already had communication troubles with Flickr API sometimes and got 502 errors. You can check Flickr services status here next time : https://secure.flickr.com/help/test

**Comment by kecimalah** [comment] 2014-11-25 17:36
For some future release would be nice if there will be some timeout for retrying communication with API. For expamle if there will be problem with internet or API, it would every minute try to connect until user close it or some max timeout like 30 min. 
Now when it fail you need to find which set was uploaded last, upload reamaining picures and then remainings sets..
But even without this uploader is best from what i found.

**Comment by syno2flickr** [comment] 2014-11-26 10:07
Ok I removed bug's tag. I noted your wish for future release.
Problem is solved, I close this issue.

**Closed as completed by syno2flickr** 2014-11-26 10:07 UTC
